// 56 lá Ẩn Phụ của bộ Tarot Huyền My: bốn bộ (Gậy, Cốc, Kiếm, Tiền), mỗi bộ 14 lá (Át, 2 đến 10, Thị Đồng, Kỵ Sĩ, Nữ Hoàng, Vua).
// Lời viết riêng, đọc theo hướng soi mình, không dự báo sự kiện. Nên nhờ người chơi Tarot lâu năm đọc lại.
// Mỗi dòng: [ba từ khóa, ý chính, câu hỏi soi mình, bước nhỏ, biểu cảm của Huyền My, không khí của cảnh vẽ].
export const SUITS = {
  gay: { vi: 'Gậy', en: 'Wands', element: 'Lửa', theme: 'đam mê, hành động, sáng tạo', color: '#ff9b54', base: 22 },
  coc: { vi: 'Cốc', en: 'Cups', element: 'Nước', theme: 'cảm xúc, quan hệ, trực giác', color: '#4fb6c9', base: 36 },
  kiem: { vi: 'Kiếm', en: 'Swords', element: 'Khí', theme: 'suy nghĩ, lời nói, sự thật', color: '#8fa6d8', base: 50 },
  tien: { vi: 'Tiền', en: 'Pentacles', element: 'Đất', theme: 'công việc, tiền bạc, sức khỏe, đời sống', color: '#7cc27a', base: 64 },
};
export const RANKS = [null, ['Át', 'Ace'], ['Hai', 'Two'], ['Ba', 'Three'], ['Bốn', 'Four'], ['Năm', 'Five'], ['Sáu', 'Six'], ['Bảy', 'Seven'], ['Tám', 'Eight'], ['Chín', 'Nine'], ['Mười', 'Ten'], ['Thị Đồng', 'Page'], ['Kỵ Sĩ', 'Knight'], ['Nữ Hoàng', 'Queen'], ['Vua', 'King']];
const SHORT = [null, 'Át', '2', '3', '4', '5', '6', '7', '8', '9', '10', 'Thị Đồng', 'Kỵ Sĩ', 'Nữ Hoàng', 'Vua'];

const DATA = {
  gay: [
    [['tia lửa mới', 'cảm hứng', 'dám bắt đầu'], 'Một ý tưởng hay cảm hứng vừa bùng lên, còn nhỏ nhưng thật. Lá bài mời bạn giữ lấy ngọn lửa ấy trước khi nó tắt.', 'Điều gì gần đây làm bạn thấy háo hức thật sự?', 'Viết ý tưởng đó lên giấy và làm bước đầu tiên nhỏ nhất.', 'hao_hung', 'dawn'],
    [['lập kế hoạch', 'nhìn xa', 'chọn hướng'], 'Bạn đã có thứ trong tay và đang nhìn ra xa để chọn hướng đi tiếp. Lá bài nói về khoảnh khắc đứng giữa điều đã có và điều muốn có.', 'Nếu mọi thứ đều khả thi, bạn muốn đi tới đâu?', 'Vẽ ra hai hướng đi, ghi một ưu điểm và một băn khoăn của mỗi hướng.', 'suy_nghi', 'dusk'],
    [['chờ thuyền về', 'mở rộng', 'kiên nhẫn'], 'Việc bạn bắt đầu đã đi xa, giờ là lúc quan sát kết quả đang tới. Lá bài khuyên nhìn rộng ra và tin vào công sức đã gieo.', 'Bạn đã gieo điều gì mà đang cần thêm thời gian để thấy kết quả?', 'Hỏi thăm tiến độ một việc đã gửi đi, hoặc chuẩn bị bước mở rộng kế tiếp.', 'chiem_nghiem', 'dusk'],
    [['ăn mừng', 'mái ấm', 'chặng hoàn thành'], 'Một chặng đã xong và đáng được ăn mừng cùng người thân hoặc bạn bè. Lá bài nói về cảm giác an toàn của nơi mình thuộc về.', 'Điều gì xứng đáng được ăn mừng, dù nhỏ?', 'Tổ chức một buổi gặp nhỏ hoặc tự thưởng mình một điều giản dị.', 'vui', 'flower'],
    [['va chạm', 'cạnh tranh', 'nhiều ý kiến'], 'Nhiều ý kiến và năng lượng đang va vào nhau, có thể là tranh luận hoặc cạnh tranh. Va chạm lành mạnh làm mọi người sắc nét hơn, miễn là có luật chơi.', 'Bạn đang tranh với ai, và điều bạn thật sự muốn bảo vệ là gì?', 'Chọn một bất đồng và thử nói điều bạn cần, thay vì điều bạn phản đối.', 'tran_tro', 'flame'],
    [['chiến thắng', 'được ghi nhận', 'tự tin'], 'Công sức của bạn được nhìn thấy. Lá bài nói về niềm vui khi được ghi nhận, sự tự tin đi cùng nó, và việc cảm ơn người đã đồng hành.', 'Bạn đã tự ghi nhận công sức của mình chưa, hay chỉ chờ người khác?', 'Viết ra một thành quả gần đây và cảm ơn một người đã giúp.', 'cuoi_tit', 'day'],
    [['giữ lập trường', 'bảo vệ điều mình tin', 'kiên định'], 'Bạn đang ở vị trí cao hơn nhưng phải giữ nó trước nhiều thử thách. Lá bài nói về việc đứng vững vì điều mình tin mà không cần thắng mọi cuộc cãi.', 'Điều nào đáng giữ đến cùng, điều nào có thể nhường?', 'Chọn một điều bạn sẽ không nhượng bộ, để các điều còn lại linh hoạt.', 'nghiem_tuc', 'dusk'],
    [['tốc độ', 'tin tức tới', 'đà chuyển động'], 'Mọi việc đang chuyển nhanh và thông tin dồn dập. Lá bài nhắc tận dụng đà đang có và giữ đầu óc gọn gàng.', 'Việc nào đang cần phản hồi ngay, việc nào có thể đợi?', 'Xử lý ba việc tồn đọng ngắn ngay trong hôm nay.', 'hao_hung', 'day'],
    [['mệt nhưng chưa bỏ', 'sát vạch đích', 'giữ sức'], 'Bạn đã đi qua nhiều và còn một đoạn nữa. Lá bài thừa nhận sự mệt mỏi, đồng thời nhắc rằng bạn đã đi xa hơn mình nghĩ.', 'Bạn đang gắng gượng vì điều gì, và có cần nghỉ để đi tiếp không?', 'Nghỉ ngắn có chủ đích hôm nay và nhờ một người san bớt một việc.', 'tran_tro', 'night'],
    [['gánh nặng', 'trách nhiệm', 'chia bớt'], 'Bạn đang gánh nhiều việc cùng lúc, có thể do chính mình nhận vào. Lá bài nhắc rằng đặt bớt xuống cũng là một cách để đi tiếp.', 'Phần nào trong gánh này là của bạn, phần nào bạn nhận hộ?', 'Chọn một việc để giao lại, hoãn hoặc bỏ đi.', 'tran_tro', 'dusk'],
    [['tò mò', 'thử nghiệm', 'tin vui nhỏ'], 'Một phần nhiệt huyết trong bạn muốn khám phá. Lá bài nói về sự tò mò, ý tưởng mới và dám thử khi chưa cần giỏi.', 'Bạn muốn thử điều gì mà chưa dám vì sợ không giỏi?', 'Thử điều đó ở mức dễ nhất, như một thí nghiệm không ai chấm điểm.', 'vui', 'dawn'],
    [['hăng hái', 'lao tới', 'dễ bốc đồng'], 'Năng lượng cao, muốn đi ngay, rất hợp để khởi động nhưng dễ vội. Lá bài nhắc chọn hướng trước khi phi nước đại.', 'Nếu đi chậm hơn một nhịp, bạn có thấy rõ điều mình đang đuổi theo không?', 'Dành năm phút ghi mục tiêu của việc đang làm trước khi bắt đầu.', 'khich_le', 'flame'],
    [['ấm áp', 'tự tin', 'truyền cảm hứng'], 'Sự tự tin ấm áp của người biết mình muốn gì và khiến người khác thấy thoải mái. Lá bài mời bạn tỏa sáng theo cách riêng.', 'Bạn sẽ cư xử thế nào nếu thật sự tin vào giá trị của mình?', 'Nói ra một ý kiến hoặc đề xuất mà bạn thường giữ lại.', 'vui', 'day'],
    [['lãnh đạo', 'tầm nhìn', 'truyền lửa'], 'Người dẫn dắt có tầm nhìn và biết truyền động lực. Lá bài nhắc dùng sức ảnh hưởng để nâng người khác lên, không để áp đặt.', 'Bạn muốn người xung quanh cảm thấy thế nào khi làm việc với bạn?', 'Nói rõ tầm nhìn của một việc cho người cùng làm, trong ba câu.', 'nghiem_tuc', 'gold'],
  ],
  coc: [
    [['cảm xúc mới', 'trái tim mở', 'yêu thương'], 'Một dòng cảm xúc mới đang đầy lên: tình thân, tình yêu hoặc niềm vui sáng tạo. Lá bài mời bạn mở lòng đón nhận.', 'Bạn đang sẵn lòng đón nhận điều gì vào cuộc sống?', 'Nói với một người điều bạn trân trọng ở họ.', 'an_ui', 'dawn'],
    [['kết nối', 'hòa hợp', 'trao đổi'], 'Hai bên gặp nhau trên sự tôn trọng. Có thể là tình cảm, bạn bè hoặc một đối tác; lá bài nói về cho và nhận cân bằng.', 'Mối quan hệ nào của bạn đang cần cân bằng hơn?', 'Chủ động hỏi thăm một người và lắng nghe trọn vẹn.', 'e_then', 'flower'],
    [['vui cùng nhau', 'bạn bè', 'ăn mừng'], 'Niềm vui khi ở cạnh những người hợp với mình. Lá bài nhắc nuôi dưỡng cộng đồng nhỏ của bạn.', 'Lần cuối bạn cười thật nhiều cùng bạn bè là khi nào?', 'Hẹn một buổi gặp gỡ nhẹ nhàng trong tuần này.', 'cuoi_tit', 'flower'],
    [['chán', 'cơ hội đang chờ', 'nhìn lại'], 'Bạn có thể đang thấy chán hoặc chưa hài lòng với điều đang có, và bỏ lỡ một lời mời nhỏ ở bên cạnh. Lá bài hỏi bạn thật sự muốn gì.', 'Bạn đang chờ điều gì xuất hiện, trong khi điều đang ở trước mặt bị bỏ qua?', 'Nhận một lời mời hoặc thử một điều mới nhỏ trong tuần này.', 'suy_nghi', 'dusk'],
    [['tiếc nuối', 'mất mát', 'vẫn còn điều ở lại'], 'Nỗi buồn vì điều đã đổ vỡ là có thật và xứng được trải qua. Lá bài cũng chỉ ra những chiếc cốc vẫn còn đứng đó sau lưng bạn.', 'Bạn đang nhìn điều đã mất hay điều còn lại?', 'Cho phép mình buồn một chút, rồi gọi tên một điều vẫn còn với bạn.', 'buon', 'rain'],
    [['hoài niệm', 'tuổi thơ', 'sự ngây thơ'], 'Ký ức đẹp và những mối quan hệ cũ trở lại. Lá bài nói về sự ấm áp của quá khứ và cách đem nó vào hiện tại một cách tử tế.', 'Ký ức nào đang muốn được ghé thăm lại?', 'Nhắn cho một người từ ngày cũ, hoặc xem lại một bức ảnh quen.', 'xuc_dong', 'flower'],
    [['nhiều lựa chọn', 'mơ mộng', 'cần tỉnh táo'], 'Nhiều viễn cảnh lấp lánh trước mặt, cái nào cũng hấp dẫn. Lá bài nhắc phân biệt điều thật sự khả thi với điều chỉ đẹp trong tưởng tượng.', 'Trong các lựa chọn này, cái nào bạn sẽ bắt đầu làm ngay?', 'Chọn một lựa chọn và viết ba bước đầu tiên để thử.', 'tran_tro', 'night'],
    [['rời đi', 'tìm ý nghĩa sâu hơn', 'buông điều chưa đủ'], 'Dù đã có nhiều thứ, bạn thấy còn thiếu một điều gì đó và muốn đi tìm. Lá bài nói về can đảm bước khỏi thứ không còn nuôi dưỡng mình.', 'Bạn đang rời bỏ điều gì, và đang đi tìm điều gì?', 'Viết ra điều bạn đang thiếu thật sự, rồi thử một bước nhỏ hướng tới nó.', 'chiem_nghiem', 'night'],
    [['hài lòng', 'điều ước thành', 'biết ơn'], 'Cảm giác đủ đầy và hài lòng với điều đã có. Lá bài mời bạn dừng lại thưởng thức thành quả.', 'Điều gì trong cuộc sống hiện tại bạn thấy đáng biết ơn?', 'Liệt kê ba điều làm bạn hài lòng gần đây.', 'cuoi_tit', 'gold'],
    [['gia đình', 'hạnh phúc trọn vẹn', 'gắn kết'], 'Hình ảnh của một mái ấm hòa thuận. Lá bài nói về sự gắn bó và niềm vui giản dị khi cùng nhau.', 'Mái ấm thật sự với bạn trông như thế nào?', 'Dành một bữa ăn không điện thoại cùng người thân.', 'vui', 'flower'],
    [['trực giác mới', 'thông điệp dịu dàng', 'mơ mộng'], 'Một cảm xúc hay thông điệp nhỏ đến bất ngờ. Lá bài mời bạn mở lòng và nghe điều nhạy cảm bên trong.', 'Bạn đang bỏ qua tiếng nói nhỏ nào ở bên trong?', 'Viết ra một cảm xúc vừa thoáng qua, không phán xét.', 'e_then', 'dawn'],
    [['lãng mạn', 'lời mời', 'theo trái tim'], 'Người mang đến lời mời, tình cảm hoặc ý tưởng đầy cảm hứng. Lá bài khuyên theo trái tim nhưng đừng quên đôi chân đang đứng ở đâu.', 'Điều bạn đang theo đuổi bằng trái tim có hợp với thực tế không?', 'Đáp lại một lời mời hoặc bày tỏ một cảm xúc chân thành, ở mức vừa đủ.', 'an_ui', 'day'],
    [['đồng cảm', 'nhạy cảm', 'chăm sóc'], 'Người thấu cảm, biết lắng nghe cảm xúc của mình và của người khác. Lá bài nhắc giữ ranh giới để lòng tốt không cạn.', 'Bạn đang nhận phần cảm xúc nào của người khác?', 'Hít sâu và hỏi mình cần gì trước khi giúp người khác.', 'dong_cam', 'calm'],
    [['trưởng thành cảm xúc', 'điềm tĩnh', 'khéo léo'], 'Sự cân bằng giữa lý trí và cảm xúc, bình tĩnh khi sóng gió. Lá bài nói về cách xử lý cảm xúc một cách chín chắn.', 'Khi cảm xúc dâng lên, bạn thường làm gì?', 'Thử gọi tên cảm xúc bằng một từ trước khi phản ứng.', 'tinh_tam', 'calm'],
  ],
  kiem: [
    [['sáng tỏ', 'sự thật', 'ý tưởng sắc'], 'Một ý nghĩ rõ như tia chớp, giúp gọi tên điều đang mơ hồ. Lá bài nói về trí óc sáng và sự thật được nói ra nhẹ nhàng.', 'Điều gì bạn đã biết nhưng chưa nói ra?', 'Viết một câu thật ngắn tóm tắt vấn đề bạn đang nghĩ.', 'nghiem_tuc', 'day'],
    [['bế tắc', 'chưa muốn chọn', 'che mắt'], 'Hai điều đang cân bằng và bạn nhắm mắt để khỏi phải chọn. Lá bài nhắc mở mắt nhìn thông tin còn thiếu.', 'Điều gì khiến bạn né nhìn thẳng vào lựa chọn này?', 'Tìm thêm một thông tin thật, rồi quyết định trong ba ngày.', 'tran_tro', 'night'],
    [['đau lòng', 'chia ly', 'thừa nhận nỗi đau'], 'Một nỗi đau tinh thần có thật, như lời nói hay sự việc làm tim thắt lại. Lá bài cho phép bạn đau, đây cũng là bước đầu của chữa lành.', 'Điều gì bạn cần được an ủi ngay lúc này?', 'Kể nỗi buồn với một người tin cậy hoặc viết nó ra giấy.', 'buon', 'rain'],
    [['nghỉ ngơi', 'hồi phục', 'tạm lui'], 'Cơ thể và đầu óc cần dừng để hồi sức. Nghỉ không phải bỏ cuộc, mà là chuẩn bị cho chặng sau.', 'Bạn cần dừng điều gì để hồi sức?', 'Ngủ sớm hoặc nghỉ hẳn một buổi không việc.', 'tinh_tam', 'calm'],
    [['thắng thua', 'xung đột', 'thiệt hơn'], 'Có chuyện thắng cuộc mà mất lòng người. Lá bài hỏi có đáng không, và bạn có muốn chọn cách khác.', 'Thắng chuyện này, bạn mất gì và được gì?', 'Thử nhún một bước trong một cuộc tranh luận nhỏ.', 'nghiem_tuc', 'storm'],
    [['chuyển sang chỗ êm hơn', 'rời xa', 'tạm yên'], 'Bạn đang rời xa chuyện khó để tới vùng nước yên hơn, dù còn mang theo gánh. Lá bài nói về quá trình đi qua.', 'Bạn đang rời xa điều gì, và đang mang theo điều gì?', 'Chọn một điều không cần mang sang chặng mới và để nó lại.', 'tinh_tam', 'calm'],
    [['né tránh', 'mưu mẹo', 'nên nói thẳng'], 'Có điều đang được làm lén hoặc tránh né. Lá bài nhắc rằng nói thẳng thường nhẹ hơn tìm đường vòng.', 'Có việc nào bạn đang né, và nói thẳng sẽ ra sao?', 'Nói với người liên quan một điều bạn vẫn giấu, bằng lời nhẹ nhàng.', 'tinh_nghich', 'night'],
    [['tự trói', 'cảm giác bị kẹt', 'lối ra có thật'], 'Cảm giác bị kẹt, nhưng dây trói trong tranh khá lỏng. Nhiều khi ta bị giữ bởi niềm tin rằng mình không có lựa chọn.', 'Niềm tin nào đang giữ bạn đứng yên?', 'Viết ba lối ra có thể có, dù nhỏ hay khó.', 'tran_tro', 'dusk'],
    [['lo âu', 'trằn trọc', 'nỗi sợ ban đêm'], 'Những nỗi lo nặng nhất vào ban đêm. Lá bài cho thấy cảm xúc của bạn có thật, và cũng nhắc nỗi lo thường lớn hơn sự thật.', 'Nỗi lo nào giải quyết được, nỗi nào chỉ là tưởng tượng?', 'Viết nỗi lo ra giấy và chọn một việc nhỏ làm được vào ngày mai.', 'buon', 'night'],
    [['kết thúc đau', 'chạm đáy', 'bình minh sau đó'], 'Một chặng kết thúc, có thể đau nhưng đã xong; ở chân trời, bình minh đang lên. Lá bài nói về điểm chạm đáy và việc bắt đầu lại.', 'Điều gì đã thật sự kết thúc, và bạn cần buông nó để đi tiếp?', 'Nói lời tạm biệt với một điều đã qua bằng một lá thư không cần gửi.', 'xuc_dong', 'dawn'],
    [['tò mò trí tuệ', 'đặt câu hỏi', 'quan sát'], 'Đầu óc nhanh, thích tìm hiểu và hỏi nhiều. Lá bài nhắc nói có suy nghĩ, tránh vội phán xét.', 'Bạn muốn hiểu điều gì kỹ hơn?', 'Đặt ba câu hỏi về một chuyện bạn vẫn nghĩ là đã hiểu.', 'suy_nghi', 'day'],
    [['nhanh', 'thẳng', 'dễ gay gắt'], 'Quyết đoán, nói nhanh làm nhanh, có thể làm tổn thương người khác nếu thiếu mềm mại. Lá bài mời giữ sự thẳng thắn và thêm chút tử tế.', 'Lời nào của bạn gần đây có thể được nói nhẹ hơn?', 'Trước khi gửi một tin nhắn quan trọng, đọc lại một lần.', 'khich_le', 'storm'],
    [['rõ ràng', 'độc lập', 'thẳng thắn có chừng mực'], 'Người nhìn rõ sự thật và nói gọn, từng trải qua mất mát nên hiểu ranh giới. Lá bài nhắc cân bằng giữa lý trí và lòng ấm.', 'Bạn có thể nói điều khó bằng giọng ấm hơn không?', 'Đặt một ranh giới rõ ràng, ngắn gọn với một người.', 'nghiem_tuc', 'day'],
    [['lý trí', 'công bằng', 'quyết định'], 'Người suy nghĩ có hệ thống và quyết định dựa trên sự thật. Lá bài nhắc lắng nghe cả cảm xúc để quyết định có tình có lý.', 'Quyết định này cần thêm dữ kiện hay thêm can đảm?', 'Viết ra tiêu chí cho một quyết định đang chờ.', 'nghiem_tuc', 'storm'],
  ],
  tien: [
    [['cơ hội thực tế', 'hạt giống', 'nền tảng'], 'Một cơ hội cụ thể về công việc, tiền bạc hoặc sức khỏe, như hạt giống để vun trồng. Lá bài khuyên bắt đầu thực tế.', 'Hạt giống nào bạn muốn vun trồng trong ba tháng tới?', 'Làm một bước thực tế nhỏ, như mở khoản tiết kiệm hoặc lên lịch tập.', 'vui', 'dawn'],
    [['cân bằng', 'xoay xở', 'linh hoạt'], 'Bạn đang tung hứng nhiều việc và cần giữ nhịp. Lá bài nhắc linh hoạt và biết việc nào được ưu tiên.', 'Việc nào đang chiếm nhiều sức hơn mức cần?', 'Chọn ba việc ưu tiên cho tuần này, phần còn lại để sau.', 'tinh_nghich', 'day'],
    [['làm việc nhóm', 'tay nghề', 'được góp ý'], 'Kỹ năng được chắp cánh khi làm cùng người khác. Lá bài nói về hợp tác và học hỏi từ góp ý.', 'Ai có thể giúp tay nghề của bạn tiến một bước?', 'Xin một góp ý cụ thể cho việc đang làm.', 'chia_se', 'day'],
    [['giữ chặt', 'an toàn', 'nới tay'], 'Muốn giữ chắc điều đang có là tự nhiên, nhưng giữ quá chặt có thể làm bạn cứng nhắc. Lá bài hỏi mức an toàn nào là đủ.', 'Điều gì bạn đang nắm quá chặt vì sợ mất?', 'Chi hoặc cho đi một khoản nhỏ có ý nghĩa mà bạn vẫn thấy yên tâm.', 'nghiem_tuc', 'gold'],
    [['thiếu thốn', 'cô đơn lúc khó', 'nhận giúp đỡ'], 'Giai đoạn thiếu thốn hoặc thấy mình bị bỏ lại. Lá bài nhắc rằng trong tranh có một khung cửa sáng ở gần: sự giúp đỡ có thể ở rất gần.', 'Bạn đang ngại xin giúp đỡ điều gì?', 'Nhắn cho một người tin cậy và nói thật về hoàn cảnh của mình.', 'buon', 'snow'],
    [['cho và nhận', 'chia sẻ', 'công bằng'], 'Dòng chảy cho đi và nhận lại. Lá bài nói về sự rộng rãi có chừng mực và biết nhận khi cần.', 'Bạn đang cho quá nhiều hay nhận quá ít?', 'Làm một việc tốt nhỏ không mong đền đáp, hoặc nhận một lời giúp.', 'dong_cam', 'gold'],
    [['chờ kết quả', 'đánh giá lại', 'kiên nhẫn'], 'Bạn đã bỏ nhiều công, giờ nhìn thành quả và tự hỏi có đáng không. Lá bài khuyên đánh giá lại cách làm trước khi tiếp tục.', 'Công sức này đang đem lại điều bạn thật sự muốn không?', 'Xem lại một mục tiêu dài hạn và chỉnh nhẹ cách làm.', 'suy_nghi', 'dusk'],
    [['rèn tay nghề', 'chăm chỉ', 'tỉ mỉ'], 'Kiên nhẫn lặp đi lặp lại để giỏi lên. Lá bài khen sự chăm chỉ và nhắc nghỉ khi cần.', 'Kỹ năng nào bạn muốn giỏi hơn một nấc?', 'Dành đều ba mươi phút mỗi ngày cho kỹ năng đó trong một tuần.', 'nghiem_tuc', 'day'],
    [['tự lập', 'thành quả', 'tận hưởng'], 'Thành quả của việc tự mình cố gắng. Lá bài mời bạn tận hưởng sự thoải mái đã gây dựng và tin vào sức mình.', 'Bạn có cho phép mình tận hưởng những gì đã làm được không?', 'Làm một điều thư giãn dành riêng cho bạn, không áy náy.', 'vui', 'flower'],
    [['bền vững', 'gia đình', 'di sản'], 'Nền tảng dài lâu về gia đình, tài chính và giá trị. Lá bài nói về những điều bền vững được xây qua nhiều năm.', 'Bạn muốn xây điều gì có thể bền hơn chính bạn?', 'Trò chuyện với người thân về một kế hoạch lâu dài.', 'xuc_dong', 'gold'],
    [['học điều thực tế', 'tò mò vật chất', 'bắt đầu nhỏ'], 'Một người học việc háo hức với kỹ năng hoặc kế hoạch mới. Lá bài khuyên học đều đặn và kiên nhẫn.', 'Bạn muốn học điều thực tế nào?', 'Đăng ký một lớp, một bài học hoặc một thói quen nhỏ.', 'vui', 'flower'],
    [['chắc chắn', 'đều đặn', 'chậm mà chắc'], 'Người làm việc cẩn thận và đáng tin, tiến từng bước vững chắc. Lá bài khen sự kiên trì và nhắc đừng sợ thử cái mới.', 'Sự cẩn thận của bạn đang giúp hay đang giữ bạn lại?', 'Hoàn thành một việc dang dở theo từng bước nhỏ.', 'nghiem_tuc', 'day'],
    [['chăm sóc thực tế', 'ấm cúng', 'nuôi dưỡng'], 'Người biết chăm sóc nhà cửa, sức khỏe và công việc một cách thực tế. Lá bài nhắc cân bằng giữa lo cho người khác và lo cho mình.', 'Bạn đã lo cho nhu cầu cơ bản của mình tới đâu?', 'Chuẩn bị một bữa ăn hoặc một góc ấm cúng cho chính mình.', 'an_ui', 'flower'],
    [['thịnh vượng', 'ổn định', 'quản lý tốt'], 'Người xây nền vững và biết quản lý nguồn lực. Lá bài nhắc rằng giàu có thật là thấy đủ và biết chia sẻ.', 'Với bạn, thế nào là đủ?', 'Xem lại một khoản chi hoặc cam kết lớn và chỉnh theo điều bạn coi trọng.', 'tinh_tam', 'gold'],
  ],
};

export const MINOR = Object.entries(DATA).flatMap(([suit, rows]) => rows.map(([keys, gist, mirror, step, emo, mood], i) => {
  const s = SUITS[suit], rank = i + 1, [vi, en] = RANKS[rank];
  return {
    id: s.base + i, minor: true, suit, rank, mood, roman: `${SHORT[rank]} · ${s.vi}`, name: `${vi} ${s.vi}`, en: `${en} of ${s.en}`,
    keys, gist, mirror, step, emo, suitNote: `Bộ ${s.vi} (${s.element}: ${s.theme})`,
  };
}));
